### PR TITLE
message clipper added

### PR DESCRIPTION
**Pull request by cimplesid**

### CODE REVIEW

**Comment by pishguy** [comment]
@cimplesid how about border radius for corners?

message

**Comment by cimplesid** [comment]
try decoration property of container

**Comment by pishguy** [comment]
@cimplesid and how about corners of Triangle?

**Comment by cimplesid** [comment]
> @cimplesid and how about corners of Triangle?

need to work on it then

**Comment by cimplesid** [comment]
> @cimplesid and how about corners of Triangle?

@MahdiPishguy  maybe now it is ok

**Pull request merged**
